-- MySQL Script generated by MySQL Workbench
-- 11/03/15 15:32:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema padrao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema padrao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `padrao` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `padrao` ;

-- -----------------------------------------------------
-- Table `padrao`.`tb_estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padrao`.`tb_estados` (
  `est_id` INT(11) NOT NULL,
  `est_sigla` VARCHAR(2) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `est_nome` VARCHAR(72) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`est_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `padrao`.`tb_cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padrao`.`tb_cidades` (
  `cid_id` INT(11) NOT NULL,
  `cid_nome` VARCHAR(72) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `cid_cep` VARCHAR(8) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `est_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cid_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `padrao`.`tb_colaboradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padrao`.`tb_colaboradores` (
  `col_id` BIGINT NOT NULL AUTO_INCREMENT,
  `col_nome` VARCHAR(255) NULL,
  `col_cpf` VARCHAR(15) NULL,
  `col_rg` VARCHAR(25) NULL,
  `col_email` VARCHAR(255) NULL,
  `col_sexo` CHAR(1) NULL,
  `col_endereco` VARCHAR(255) NULL,
  `col_num` VARCHAR(10) NULL,
  `col_bairro` VARCHAR(255) NULL,
  `col_complemento` VARCHAR(255) NULL,
  `col_cep` VARCHAR(10) NULL,
  `col_telefone` VARCHAR(15) NULL,
  `col_celular` VARCHAR(15) NULL,
  `col_senha` VARCHAR(45) NULL,
  `col_dtNasc` DATE NULL,
  `est_id` INT(11) NULL,
  `cid_id` INT(11) NULL,
  PRIMARY KEY (`col_id`),
  INDEX `fk_tb_colaboradores_tb_estados1_idx` (`est_id` ASC),
  INDEX `fk_tb_colaboradores_tb_cidades1_idx` (`cid_id` ASC),
  CONSTRAINT `fk_tb_colaboradores_tb_estados1`
    FOREIGN KEY (`est_id`)
    REFERENCES `padrao`.`tb_estados` (`est_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_colaboradores_tb_cidades1`
    FOREIGN KEY (`cid_id`)
    REFERENCES `padrao`.`tb_cidades` (`cid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao`.`tb_area_atuacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padrao`.`tb_area_atuacao` (
  `area_id` INT NOT NULL AUTO_INCREMENT,
  `area_nome` VARCHAR(100) NULL,
  PRIMARY KEY (`area_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao`.`tb_vagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padrao`.`tb_vagas` (
  `vag_id` INT NOT NULL AUTO_INCREMENT,
  `vag_cargo` VARCHAR(100) NULL,
  `vag_salario` VARCHAR(45) NULL,
  `vag_descricao` LONGTEXT NULL,
  `vag_requisitos` LONGTEXT NULL,
  `vag_ativa` CHAR(1) NULL,
  `area_id` INT NULL,
  PRIMARY KEY (`vag_id`),
  INDEX `fk_tb_vagas_tb_area_atuacao_idx` (`area_id` ASC),
  CONSTRAINT `fk_tb_vagas_tb_area_atuacao`
    FOREIGN KEY (`area_id`)
    REFERENCES `padrao`.`tb_area_atuacao` (`area_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao`.`tb_candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padrao`.`tb_candidato` (
  `can_id` BIGINT NOT NULL AUTO_INCREMENT,
  `can_cpf` VARCHAR(15) NULL,
  `can_nome` VARCHAR(250) NULL,
  `can_email` VARCHAR(255) NULL,
  `can_dtNasc` DATE NULL,
  `can_sexo` CHAR(1) NULL,
  `can_estadoCivil` VARCHAR(45) NULL,
  `can_fonePreferencial` VARCHAR(45) NULL,
  `can_foneResidencial` VARCHAR(45) NULL,
  `can_foneCelular` VARCHAR(45) NULL,
  `can_foneComercial` VARCHAR(45) NULL,
  `can_foneRamal` VARCHAR(45) NULL,
  `can_foneFax` VARCHAR(45) NULL,
  `can_facebook` VARCHAR(255) NULL,
  `can_skype` VARCHAR(255) NULL,
  `can_linkedin` VARCHAR(255) NULL,
  `can_twitter` VARCHAR(255) NULL,
  `can_deficiencia` CHAR(1) NULL,
  `can_qualDef` VARCHAR(255) NULL,
  `can_cep` VARCHAR(45) NULL,
  `can_endereco` VARCHAR(255) NULL,
  `can_num` VARCHAR(10) NULL,
  `can_bairro` VARCHAR(255) NULL,
  `can_complemento` LONGTEXT NULL,
  `can_superior` VARCHAR(45) NULL,
  `can_qualSup` VARCHAR(255) NULL,
  `can_resumo` LONGTEXT NULL,
  `cid_id` INT(11) NULL,
  `est_id` INT(11) NULL,
  PRIMARY KEY (`can_id`),
  INDEX `fk_tb_candidato_tb_cidades1_idx` (`cid_id` ASC),
  INDEX `fk_tb_candidato_tb_estados1_idx` (`est_id` ASC),
  CONSTRAINT `fk_tb_candidato_tb_cidades1`
    FOREIGN KEY (`cid_id`)
    REFERENCES `padrao`.`tb_cidades` (`cid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_candidato_tb_estados1`
    FOREIGN KEY (`est_id`)
    REFERENCES `padrao`.`tb_estados` (`est_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao`.`tb_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padrao`.`tb_cursos` (
  `cur_id` BIGINT NOT NULL AUTO_INCREMENT,
  `cur_titulo` VARCHAR(150) NULL,
  `cur_ano` VARCHAR(45) NULL,
  `can_id` BIGINT NULL,
  PRIMARY KEY (`cur_id`),
  INDEX `fk_tbCursos_tbCandidato_idx` (`can_id` ASC),
  CONSTRAINT `fk_tbCursos_tbCandidato`
    FOREIGN KEY (`can_id`)
    REFERENCES `padrao`.`tb_candidato` (`can_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao`.`tb_experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padrao`.`tb_experiencia` (
  `exp_id` INT NOT NULL AUTO_INCREMENT,
  `exp_empresa` VARCHAR(255) NULL,
  `exp_cargo` VARCHAR(150) NULL,
  `exp_localidade` VARCHAR(150) NULL,
  `exp_periodoDe` VARCHAR(10) NULL,
  `exp_periodoAte` VARCHAR(10) NULL,
  `exp_descricao` LONGTEXT NULL,
  `can_id` BIGINT NULL,
  PRIMARY KEY (`exp_id`),
  INDEX `fk_tbExperiencia_tbCandidato1_idx` (`can_id` ASC),
  CONSTRAINT `fk_tbExperiencia_tbCandidato1`
    FOREIGN KEY (`can_id`)
    REFERENCES `padrao`.`tb_candidato` (`can_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao`.`tb_candidato_has_tb_vagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padrao`.`tb_candidato_has_tb_vagas` (
  `can_id` BIGINT NULL,
  `vag_id` INT NULL,
  INDEX `fk_tb_candidato_has_tb_vagas_tb_vagas1_idx` (`vag_id` ASC),
  INDEX `fk_tb_candidato_has_tb_vagas_tb_candidato1_idx` (`can_id` ASC),
  CONSTRAINT `fk_tb_candidato_has_tb_vagas_tb_candidato1`
    FOREIGN KEY (`can_id`)
    REFERENCES `padrao`.`tb_candidato` (`can_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_candidato_has_tb_vagas_tb_vagas1`
    FOREIGN KEY (`vag_id`)
    REFERENCES `padrao`.`tb_vagas` (`vag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao`.`tb_banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padrao`.`tb_banner` (
  `ban_id` INT NOT NULL AUTO_INCREMENT,
  `ban_sequencia` INT NULL,
  `ban_titulo` VARCHAR(45) NULL,
  `ban_imagem` VARCHAR(255) NULL,
  `ban_thumb` VARCHAR(255) NULL,
  `ban_ativo` CHAR(1) NULL,
  PRIMARY KEY (`ban_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao`.`tb_galerias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padrao`.`tb_galerias` (
  `gal_id` INT NOT NULL AUTO_INCREMENT,
  `gal_titulo` VARCHAR(255) NULL,
  `gal_descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`gal_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao`.`tb_imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padrao`.`tb_imagens` (
  `img_id` BIGINT NOT NULL AUTO_INCREMENT,
  `img_nome` VARCHAR(255) NULL,
  `img_thumb` VARCHAR(255) NULL,
  `img_alt` VARCHAR(255) NULL,
  `img_titulo` VARCHAR(255) NULL,
  `gal_id` INT NULL,
  PRIMARY KEY (`img_id`),
  INDEX `fk_tb_imagens_tb_galerias1_idx` (`gal_id` ASC),
  CONSTRAINT `fk_tb_imagens_tb_galerias1`
    FOREIGN KEY (`gal_id`)
    REFERENCES `padrao`.`tb_galerias` (`gal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao`.`tb_conteudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padrao`.`tb_conteudo` (
  `con_id` INT NOT NULL AUTO_INCREMENT,
  `con_titulo` VARCHAR(150) NULL,
  `con_sequencia` INT NULL,
  `con_img_destaque` VARCHAR(255) NULL,
  `con_conteudo` LONGTEXT NULL,
  `con_palavras_chaves` LONGTEXT NULL,
  `con_descricao` LONGTEXT NULL,
  PRIMARY KEY (`con_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao`.`tb_fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padrao`.`tb_fotos` (
  `fot_id` BIGINT NOT NULL AUTO_INCREMENT,
  `fot_nome` VARCHAR(255) NULL,
  `fot_link` VARCHAR(255) NULL,
  `fot_alt` VARCHAR(100) NULL,
  `fot_thumb` VARCHAR(255) NULL,
  PRIMARY KEY (`fot_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao`.`tb_noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padrao`.`tb_noticias` (
  `not_id` BIGINT NOT NULL AUTO_INCREMENT,
  `not_titulo` VARCHAR(150) NULL,
  `not_linhafina` LONGTEXT NULL,
  `not_autor` VARCHAR(255) NULL,
  `not_tipo` VARCHAR(45) NULL,
  `not_texto` LONGTEXT NULL,
  `not_fonte` VARCHAR(255) NULL,
  `not_linkfonte` VARCHAR(255) NULL,
  `not_img_destaque` VARCHAR(255) NULL,
  PRIMARY KEY (`not_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padrao`.`tb_configuracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padrao`.`tb_configuracao` (
  `conf_id` INT NOT NULL AUTO_INCREMENT,
  `conf_cep` VARCHAR(45) NULL,
  `conf_endereco` VARCHAR(255) NULL,
  `conf_num` INT NULL,
  `conf_bairro` VARCHAR(255) NULL,
  `conf_complemento` VARCHAR(255) NULL,
  `conf_telefone` VARCHAR(20) NULL,
  `conf_celular` VARCHAR(20) NULL,
  `conf_email` VARCHAR(150) NULL,
  `conf_mapa` LONGTEXT NULL,
  `conf_facebook` VARCHAR(255) NULL,
  `conf_twitter` VARCHAR(255) NULL,
  `conf_linkedin` VARCHAR(255) NULL,
  `conf_instagram` VARCHAR(255) NULL,
  `conf_googleplus` VARCHAR(255) NULL,
  `conf_youtube` VARCHAR(255) NULL,
  `conf_hora_atendimento` LONGTEXT NULL,
  `cid_id` INT(11) NOT NULL,
  `est_id` INT(11) NOT NULL,
  PRIMARY KEY (`conf_id`),
  INDEX `fk_tb_configuracao_tb_cidades1_idx` (`cid_id` ASC),
  INDEX `fk_tb_configuracao_tb_estados1_idx` (`est_id` ASC),
  CONSTRAINT `fk_tb_configuracao_tb_cidades1`
    FOREIGN KEY (`cid_id`)
    REFERENCES `padrao`.`tb_cidades` (`cid_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_configuracao_tb_estados1`
    FOREIGN KEY (`est_id`)
    REFERENCES `padrao`.`tb_estados` (`est_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
